// src/screens/auth/ProviderSignupScreen.tsx
//
// Service provider registration. Only reachable through an invitation link
// (…/provider/signup?invite=TOKEN) generated by an admin. There is deliberately
// no route to this screen from anywhere in the public app.
//
// The invite is checked here to give a clear message, but that check is only
// for the user's benefit — the Firestore rules are what actually refuse an
// invalid, expired, or already-used invite.

import React, { useEffect, useState } from 'react';
import {
  View,
  StyleSheet,
  ScrollView,
  KeyboardAvoidingView,
  Platform,
  ActivityIndicator,
  Image,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import Text from '@/components/app-text';
import InputField from '@/components/InputField';
import Button from '@/components/Button';
import ApplianceSelector from '@/components/ApplianceSelector';
import LanguageSwitcher from '@/components/LanguageSwitcher';
import { useAuth } from '@/context/AuthContext';
import { useLanguage } from '@/i18n/LanguageContext';
import { getAuthErrorMessage } from '@/services/authService';
import { getInvite, inviteStatus, InviteStatus, ProviderInvite } from '@/services/inviteService';
import { getEmailError, getPasswordError } from '@/utils/validation';
import { colors, radius, spacing, shadow, typography } from '@/theme/theme';
import type { AuthStackParamList } from '@/navigation/AuthNavigator';

type Props = NativeStackScreenProps<AuthStackParamList, 'ProviderSignup'>;

/** What to tell someone whose link can't be used, per reason. */
const BLOCKED: Record<Exclude<InviteStatus, 'valid'>, { title: string; body: string }> = {
  invalid: {
    title: 'Invalid invitation',
    body: 'This invitation link is not valid. Please check the link or ask the DEEM team for a new one.',
  },
  expired: {
    title: 'Invitation expired',
    body: 'This invitation has expired. Please ask the DEEM team to send you a new link.',
  },
  used: {
    title: 'Invitation already used',
    body: 'This invitation has already been used to create an account. If that was you, please log in.',
  },
  revoked: {
    title: 'Invitation cancelled',
    body: 'This invitation has been cancelled. Please contact the DEEM team if you think this is a mistake.',
  },
};

export default function ProviderSignupScreen({ route, navigation }: Props) {
  const { registerProvider } = useAuth();
  const { t } = useLanguage();
  const token = route.params?.invite ?? '';

  const [checking, setChecking] = useState(true);
  const [invite, setInvite] = useState<ProviderInvite | null>(null);
  const [status, setStatus] = useState<InviteStatus>('invalid');

  const [businessName, setBusinessName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [appliances, setAppliances] = useState<string[]>([]);
  const [address, setAddress] = useState('');
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [formError, setFormError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    let cancelled = false;
    getInvite(token).then((inv) => {
      if (cancelled) return;
      setInvite(inv);
      setStatus(inviteStatus(inv));
      // An invite issued to a specific address fixes the account's email.
      if (inv?.email) setEmail(inv.email);
      setChecking(false);
    });
    return () => {
      cancelled = true;
    };
  }, [token]);

  function validate(): boolean {
    const next: Record<string, string> = {};
    if (!businessName.trim()) next.businessName = 'Please enter your business name.';
    const emailProblem = getEmailError(email);
    if (emailProblem) next.email = emailProblem;
    const passwordProblem = getPasswordError(password);
    if (passwordProblem) next.password = passwordProblem;
    if (password && password !== confirm) next.confirm = 'Passwords do not match.';
    if (appliances.length === 0) next.appliances = 'Please choose at least one service you offer.';
    setErrors(next);
    return Object.keys(next).length === 0;
  }

  async function handleSubmit() {
    setFormError('');
    if (!validate()) return;
    setSubmitting(true);
    try {
      await registerProvider(token, {
        businessName: businessName.trim(),
        email: email.trim(),
        password,
        appliances,
        address,
      });
      // Success switches the app to the provider interface automatically.
    } catch (e: any) {
      const code: string = e?.message ?? '';
      if (code.startsWith('INVITE_') && code !== 'INVITE_EMAIL_MISMATCH') {
        // Someone else used it, or it lapsed, while this form was open.
        setStatus(code.replace('INVITE_', '').toLowerCase() as InviteStatus);
      } else if (code === 'INVITE_EMAIL_MISMATCH') {
        setFormError('This invitation was issued for a different email address.');
      } else {
        setFormError(getAuthErrorMessage(e, 'register'));
      }
    } finally {
      setSubmitting(false);
    }
  }

  const header = (
    <View style={styles.topBar}>
      <View />
      <LanguageSwitcher style={{ alignSelf: 'center' }} />
    </View>
  );

  if (checking) {
    return (
      <View style={styles.center}>
        <ActivityIndicator color={colors.primary} />
        <Text style={styles.checkingText}>{t('Checking your invitation…')}</Text>
      </View>
    );
  }

  if (status !== 'valid') {
    const msg = BLOCKED[status];
    return (
      <ScrollView style={styles.root} contentContainerStyle={styles.container}>
        {header}
        <View style={styles.card}>
          <View style={styles.blockedIcon}>
            <Ionicons name="lock-closed-outline" size={30} color={colors.danger} />
          </View>
          <Text style={styles.blockedTitle}>{t(msg.title)}</Text>
          <Text style={styles.blockedBody}>{t(msg.body)}</Text>
          {status === 'used' ? (
            <Button
              label={t('Log in')}
              onPress={() => navigation.navigate('Login')}
              style={{ marginTop: spacing.lg }}
            />
          ) : null}
        </View>
      </ScrollView>
    );
  }

  return (
    <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView style={styles.root} contentContainerStyle={styles.container}>
        {header}
        <Image
          source={require('../../../assets/logo.png')}
          style={styles.logo}
          resizeMode="contain"
        />
        <Text style={styles.title}>{t('Service Provider Registration')}</Text>
        <Text style={styles.subtitle}>
          {t("You've been invited to join DEEM as a service provider.")}
        </Text>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>{t('Business details')}</Text>
          <InputField
            label={t('Business name')}
            placeholder={t('e.g. Ahmed Services')}
            value={businessName}
            onChangeText={setBusinessName}
            error={errors.businessName ? t(errors.businessName) : undefined}
          />
          <InputField
            label={t('Business address (optional)')}
            placeholder={t('Building, road, block, area')}
            value={address}
            onChangeText={setAddress}
          />

          <Text style={styles.fieldLabel}>{t('Services you offer')}</Text>
          <ApplianceSelector
            selected={appliances}
            onToggle={(id) =>
              setAppliances((prev) =>
                prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
              )
            }
          />
          {errors.appliances ? <Text style={styles.error}>{t(errors.appliances)}</Text> : null}
        </View>

        <View style={styles.card}>
          <Text style={styles.sectionTitle}>{t('Account')}</Text>
          <InputField
            label={t('Email')}
            placeholder={t('you@example.com')}
            autoCapitalize="none"
            autoCorrect={false}
            keyboardType="email-address"
            value={email}
            onChangeText={setEmail}
            // Locked when the invite was issued to a specific address.
            editable={!invite?.email}
            error={errors.email ? t(errors.email) : undefined}
          />
          {invite?.email ? (
            <Text style={styles.hint}>{t('This invitation was issued for this email address.')}</Text>
          ) : null}
          <InputField
            label={t('Password')}
            placeholder={t('At least 6 characters')}
            isPassword
            value={password}
            onChangeText={setPassword}
            error={errors.password ? t(errors.password) : undefined}
          />
          <InputField
            label={t('Confirm Password')}
            placeholder={t('Re-enter your password')}
            isPassword
            value={confirm}
            onChangeText={setConfirm}
            error={errors.confirm ? t(errors.confirm) : undefined}
          />
        </View>

        {formError ? <Text style={styles.formError}>{t(formError)}</Text> : null}

        <Button
          label={t('Create Provider Account')}
          onPress={handleSubmit}
          loading={submitting}
        />
        <Text style={styles.footnote}>
          {t('You can set your coverage areas and location from your profile after signing up.')}
        </Text>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  container: { padding: spacing.lg, paddingBottom: spacing.xxl },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.md,
    backgroundColor: colors.background,
  },
  checkingText: { ...typography.bodySecondary, textAlign: 'center' },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  logo: { width: 92, height: 92, alignSelf: 'center', marginBottom: spacing.sm },
  title: { ...typography.h2, textAlign: 'center' },
  subtitle: {
    ...typography.bodySecondary,
    textAlign: 'center',
    marginTop: spacing.xs,
    marginBottom: spacing.lg,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    ...shadow.card,
  },
  sectionTitle: { ...typography.h3, marginBottom: spacing.md },
  fieldLabel: {
    ...typography.bodySecondary,
    fontWeight: '600',
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  hint: { ...typography.caption, marginTop: -spacing.sm, marginBottom: spacing.md },
  error: { color: colors.danger, fontSize: 13, marginTop: spacing.sm },
  formError: {
    color: colors.danger,
    fontSize: 13,
    marginBottom: spacing.md,
    textAlign: 'center',
  },
  footnote: { ...typography.caption, textAlign: 'center', marginTop: spacing.md },
  blockedIcon: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FEE4E2',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: spacing.md,
  },
  blockedTitle: { ...typography.h2, textAlign: 'center' },
  blockedBody: {
    ...typography.bodySecondary,
    textAlign: 'center',
    marginTop: spacing.sm,
    lineHeight: 21,
  },
});
